@startuml

actor AllUsers
boundary LoginForm
control LoginController
entity Users

activate AllUsers

activate LoginForm
AllUsers -> LoginForm : (1) enter_login_and_pass()

activate LoginController
LoginForm -> LoginController : (2) login_request()

activate Users
LoginController -> Users : (3) verify_user()
LoginController <-- Users : (4) verify_status

alt verify_status == "False"
    LoginController --> LoginForm : (5) error
    LoginForm -> LoginForm : (6) show_error_message()
else verify_status == "True"
    LoginController --> LoginForm : (7) success
    LoginForm -> LoginForm : (8) show_success_message()
end




@enduml
