@startuml
actor AllUsers
boundary ProductsForm
control ProductsController
entity Product

AllUsers -> ProductsForm : (1) show_product_detailed_info()
activate ProductsForm

ProductsForm -> ProductsController : (2) get_product_info_by_id_request()
activate ProductsController

activate Product
ProductsController -> Product : (3) get_product_info_by_id()
ProductsController <-- Product : (4) product info

' DataBase --> ProductsController : (4) Данные о товаре


ProductsController --> ProductsForm : (5) product info
deactivate Product

ProductsForm -> ProductsForm : (6) update_form()
deactivate ProductsController

@enduml
