@startuml
actor AllUsers
boundary ProductsForm
control ProductsController
entity Product
' database DataBase

activate ProductsForm
AllUsers -> ProductsForm : (1) click_show_products()

ProductsForm -> ProductsController : (2) get_all_products_request()
activate ProductsController

' ProductsController -> DataBase : (3) Получение списка товаров
' activate DataBase

' DataBase --> ProductsController : (4) Список товаров
' deactivate DataBase

ProductsController -> Product : (5) get_all_products()
activate Product

Product --> ProductsController : (6) products
deactivate Product

ProductsController --> ProductsForm : (7) products
deactivate ProductsController

ProductsForm -> ProductsForm : (8) update_form()


@enduml
