@startuml
actor User
boundary ProductForm
control CartController
entity Cart

User -> ProductForm : (1) add_to_cart()
activate ProductForm

ProductForm -> CartController : (2) add_product_request()
activate CartController

CartController -> Cart : (3)  add_product_to_cart()
activate Cart

Cart --> CartController : (4) Подтверждение добавления
deactivate Cart

CartController --> ProductForm : (5) Уведомление об успешном добавлении
deactivate CartController

ProductForm --> ProductForm : (6) update_form()

@enduml
 