@startuml
actor User
boundary OrderForm
control OrderController
entity Order

activate OrderForm
User -> OrderForm : (1) click_cancel_order()


activate OrderController
OrderForm -> OrderController : (2) cancel_order_request()

activate Order
OrderController -> Order : (3) get_payment_status()
Order --> OrderController : (4) payment_status

alt payment_status == "False"
    OrderController -> Order : (5) cancel_order()
    OrderController <-- Order : (6) success
    OrderController --> OrderForm : (7) success
else payment_status == "True"
    OrderController --> OrderForm : (8) error
end


deactivate Order
deactivate OrderController

OrderForm -> OrderForm : (8) update_form()


@enduml
