@startuml
actor User
boundary CartForm
control OrderController
entity Cart
entity Order
' database DataBase

User -> CartForm : (1) click_create_order()
activate CartForm

CartForm -> OrderController : (2) create_order_request()
activate OrderController

OrderController -> Cart : (3) get_products_list()
activate Cart

Cart --> OrderController : (4) List<Product>
deactivate Cart

OrderController -> Order : (5) create_order()
activate Order

Order --> OrderController : (6) True
deactivate Order

' OrderController -> DataBase : (7) Сохранение заказа
' activate DataBase

' DataBase --> OrderController : (8) Подтверждение сохранения
' deactivate DataBase

OrderController --> CartForm : (7) True
deactivate OrderController

CartForm -> CartForm : (10) update_form()

@enduml