@startuml
actor Admin
boundary ProductsForm
control ProductsController
entity Product

Admin -> ProductsForm : (1) click_delete_product()
activate ProductsForm

ProductsForm -> ProductsController : (2) deletet_product_request()
activate ProductsController

activate Product
ProductsController -> Product : (3) delete_product()
ProductsController <-- Product : (4) True

' DataBase --> ProductsController : (4) Данные о товаре


ProductsController --> ProductsForm : (5) True
deactivate Product

ProductsForm -> ProductsForm : (6) update_form()
deactivate ProductsController

@enduml
