@startuml
actor Admin
boundary ProductsForm
control ProductsController
entity Product

Admin -> ProductsForm : (1) click_delete_product()
activate ProductsForm

ProductsForm -> ProductsForm : (2) deletion_question()

Admin -> ProductsForm : (3) click_delete_decision()

alt decision == Yes
    ProductsForm -> ProductsController : (4) delete_product_request()
    activate ProductsController

    activate Product
    ProductsController -> Product : (5) delete_product()
    ProductsController <-- Product : (6) True

    ProductsController --> ProductsForm : (7) True
    deactivate Product

    deactivate ProductsController
    ProductsForm -> ProductsForm : (8) update_form()
else decision == false
    ProductsForm -> ProductsForm : (9) update_form()
end
    



@enduml
