@startuml
component "Браузер" as Browser
component "Бэкенд магазина" as Backend
database "База данных магазина" as ShopDB
component "Бэкенд Банка" as BankAPI

' Взаимодействие
Browser -- Backend : HTTPS
Backend -- ShopDB : IDB
Backend -- BankAPI : HTTPS
' Browser -- BankAPI : 3D Secure (Проверка платежа)

@enduml