@startuml
actor Storekeeper
boundary ProductsForm
control ProductsController
entity Product

activate ProductsForm
Storekeeper -> ProductsForm : (1) click_update_product()
ProductsForm -> ProductsForm : (2) update_product_pop_up()
Storekeeper -> ProductsForm : (3) enter_product_count()

activate ProductsController
ProductsForm -> ProductsController : (4) update_product_request()


activate Product
ProductsController -> Product : (5) update_product()
ProductsController <-- Product : (6) product

' DataBase --> ProductsController : (4) Данные о товаре


ProductsController --> ProductsForm : (7) product
deactivate Product

ProductsForm -> ProductsForm : (6) update_form()
deactivate ProductsController

@enduml
